;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagRedirects=(OldTagName="UI.Layer.GameLayer",NewTagName="UI.Layer.Game")
+GameplayTagRedirects=(OldTagName="UI.Layer.GameMenuLayer",NewTagName="UI.Layer.GameMenu")
+GameplayTagRedirects=(OldTagName="UI.Layer.MenuLayer",NewTagName="UI.Layer.Menu")
+GameplayTagRedirects=(OldTagName="UI.Layer.ModalLayer",NewTagName="UI.Layer.Modal")
+GameplayTagRedirects=(OldTagName="UI.Layer.OverlayLayer",NewTagName="UI.Layer.Overlay")
+GameplayTagRedirects=(OldTagName="ScriptedEvent.GoToArenaCage",NewTagName="ScriptedEvent.ArenaCatch")
+GameplayTagRedirects=(OldTagName="ScriptedEvent.ArenaCatch",NewTagName="ScriptedEvent.DrumAcquisition")
+GameplayTagRedirects=(OldTagName="Comics.Animations.Subjecet",NewTagName="Comics.Animations.Subject")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Audio",DevComment="")
+GameplayTagList=(Tag="Audio.Ambience",DevComment="")
+GameplayTagList=(Tag="Audio.Ambience.Default",DevComment="")
+GameplayTagList=(Tag="Audio.Ambience.Room",DevComment="")
+GameplayTagList=(Tag="Audio.Bongo.Mock",DevComment="")
+GameplayTagList=(Tag="Audio.Camera",DevComment="")
+GameplayTagList=(Tag="Audio.Camera.Shake",DevComment="")
+GameplayTagList=(Tag="Audio.CutScene",DevComment="")
+GameplayTagList=(Tag="Audio.CutScene.StatueRage",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Curiosity",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Door",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Fruit",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Large.Push",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Lever",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Lever.Active",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Lever.Alarm",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Lever.Deactive",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Orb",DevComment="")
+GameplayTagList=(Tag="Audio.Item.Pedestal",DevComment="")
+GameplayTagList=(Tag="Audio.Item.PressurePlate",DevComment="")
+GameplayTagList=(Tag="Audio.Item.PressurePlate.Large",DevComment="")
+GameplayTagList=(Tag="Audio.Item.PressurePlate.Large.Pressed",DevComment="")
+GameplayTagList=(Tag="Audio.Item.PressurePlate.Large.Unpressed",DevComment="")
+GameplayTagList=(Tag="Audio.Item.PressurePlate.Small",DevComment="")
+GameplayTagList=(Tag="Audio.Jane.Footstep.Default",DevComment="")
+GameplayTagList=(Tag="Audio.Jane.Interact.Pet",DevComment="")
+GameplayTagList=(Tag="Audio.Jane.JumpLand",DevComment="")
+GameplayTagList=(Tag="Audio.Pongo.Footstep.Default",DevComment="")
+GameplayTagList=(Tag="Audio.Pongo.Interact.Drop",DevComment="")
+GameplayTagList=(Tag="Audio.Pongo.Interact.PickUp",DevComment="")
+GameplayTagList=(Tag="Audio.Pongo.Interact.Push",DevComment="")
+GameplayTagList=(Tag="Audio.Pongo.Pet",DevComment="")
+GameplayTagList=(Tag="Audio.Pongo.State",DevComment="")
+GameplayTagList=(Tag="Audio.UI",DevComment="")
+GameplayTagList=(Tag="Comics.Animations",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.BG",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.Details",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.FadeIn",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.FadeOut",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.MoveIn",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.Scale",DevComment="")
+GameplayTagList=(Tag="Comics.Animations.Subject",DevComment="")
+GameplayTagList=(Tag="Comics.Comics_1",DevComment="")
+GameplayTagList=(Tag="Comics.Comics_2",DevComment="")
+GameplayTagList=(Tag="Save.Doors",DevComment="")
+GameplayTagList=(Tag="Save.Doors.Z01_Room_2",DevComment="")
+GameplayTagList=(Tag="Save.Doors.Z01_Room_6",DevComment="")
+GameplayTagList=(Tag="Save.Doors.Z01_Room_3_2",DevComment="")
+GameplayTagList=(Tag="ScriptedEvent",DevComment="")
+GameplayTagList=(Tag="ScriptedEvent.DrumAcquisition",DevComment="")
+GameplayTagList=(Tag="ScriptedEvent.FinalRage",DevComment="")
+GameplayTagList=(Tag="ScriptedEvent.MoveToPosition",DevComment="")
+GameplayTagList=(Tag="ScriptedEvent.MoveToPositionAndWait",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Overlay",DevComment="")
+GameplayTagList=(Tag="UI.Layer.SettingsMenu",DevComment="")

