#include "AI/EnviromentQuerySystem/Tests/TPP_EnvQueryTest_NotInEmotionRanges.h"
#include "EnvironmentQuery/Items/EnvQueryItemType_Point.h"
#include "EnvironmentQuery/EnvQueryTypes.h"
#include "Components/SphereComponent.h"
#include "Components/TPP_EmotionalObjectComp.h"
#include "GameFramework/Actor.h"

// Constructor
UTPP_EnvQueryTest_NotInEmotionRanges::UTPP_EnvQueryTest_NotInEmotionRanges()
{
	// This test is relatively expensive because it iterates over all emotion triggers
	Cost = EEnvTestCost::High;

	// We only want to score items, not filter them out
	TestPurpose = EEnvTestPurpose::Score;

	// This test works on generated EQS points
	ValidItemType = UEnvQueryItemType_Point::StaticClass();

	// The test produces float scores 
	SetWorkOnFloatValues(true);
}

void UTPP_EnvQueryTest_NotInEmotionRanges::RunTest(FEnvQueryInstance& QueryInstance) const
{
	// Retrieve all actors containing emotional components provided by the context
	TArray<AActor*> TriggerActors;
	QueryInstance.PrepareContext(Context, TriggerActors);

	// If no triggers are found, all points are valid (score of 1)
	if (TriggerActors.Num() == 0)
	{
		for (FEnvQueryInstance::ItemIterator It(this, QueryInstance); It; ++It)
		{
			It.SetScore(TestPurpose, FilterType, 1.0f, 0.0f, 1.0f);
		}
		return;
	}
	// Iterate through every candidate point generated by EQS
	for (FEnvQueryInstance::ItemIterator It(this, QueryInstance); It; ++It)
	{
		const FVector ItemLocation = GetItemLocation(QueryInstance, It.GetIndex());

		// Minimum clearance from all emotional ranges
		float MinDistanceFromBoundary = FLT_MAX;

		// Iterate through all emotional trigger actors
		for (AActor* Actor : TriggerActors)
		{
			if (!Actor) continue;

			// Retrieve all emotional components attached to the actor
			if (UTPP_EmotionalObjectComp* Comp = Actor->GetComponentByClass<UTPP_EmotionalObjectComp>())
			{
				// Sphere center and radius
				const FVector Center = Comp->GetComponentLocation();
				const float Radius = Comp->GetScaledSphereRadius() + ExtraBuffer;

				// Distance between candidate point and sphere center
				const float Dist = bUse2D
					                   ? FVector::Dist2D(ItemLocation, Center)
					                   : FVector::Dist(ItemLocation, Center);

				// Clearance from the emotional range border
				// Negative value means the point is inside the sphere
				const float DistanceFromBoundary = Dist - Radius;

				// Keep the smallest clearance (closest sphere / worst case)
				MinDistanceFromBoundary = FMath::Min(MinDistanceFromBoundary, DistanceFromBoundary);
			}
		}

		// Convert clearance to a normalized score 
		// If no triggers were found, the point is fully valid
		const float RawScore = (MinDistanceFromBoundary == FLT_MAX)
			                       ? 1.0f
			                       : FMath::Clamp(MinDistanceFromBoundary / MaxGoodDistanceFromBoundary, 0.0f, 1.0f);

		// Apply the score to the EQS item
		It.SetScore(TestPurpose, FilterType, RawScore, 0.0f, 1.0f);
	}
}
